### ISSUE TITLE
OOM Errors

### ISSUE THREAD

**Issue by aflah02** [THU-KEG/Skill-Neuron#2]
Hey!
I was trying to run the code with a custom dataset and encountered the following error on the very first step - 

```
Random seed:  3619488719
['']
[33407, 22173]
2
2022-12-27 13:40:15,005 - INFO - trainer - Namespace(bz=128, data_path='/home/aflah20082/Skill-Neuron/data/founta', device='cuda:1', early_stop=False, epoch=4, eval_every_step=2000, from_pretrained=False, load_backbone='', lr=0.001, model_type='RobertaPrompt', num_labels=2, prompt_size=16, random_seed=0, resume_from='', save_to='/home/aflah20082/Skill-Neuron/founta', task_type='founta', verb=[''])
2022-12-27 13:40:15,006 - INFO - trainer - num_steps_per_dataset:
2022-12-27 13:40:15,006 - INFO - trainer - 204
2022-12-27 13:40:15,006 - INFO - trainer - total_steps:
2022-12-27 13:40:15,006 - INFO - trainer - 816
2022-12-27 13:40:15,006 - INFO - trainer - num_train_epochs:
2022-12-27 13:40:15,006 - INFO - trainer - 4
A (12324241408, 51041468416)
Epoch:   0%|                                              | 0/4 [00:00<?, ?it/s]
Iteration:   0%|                                        | 0/204 [00:00<?, ?it/s]B (12324241408, 51041468416)
Iteration:   0%|                                        | 0/204 [00:00<?, ?it/s]
Epoch:   0%|                                              | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/aflah20082/Skill-Neuron/src/train.py", line 62, in <module>
    main()
  File "/home/aflah20082/Skill-Neuron/src/train.py", line 59, in main
    t.train(train, valid, test, num_train_epochs = args.epoch)
  File "/home/aflah20082/Skill-Neuron/src/trainer.py", line 116, in train
    loss = self.criterion(self.mlm_train_step(batch),labels.long())
  File "/home/aflah20082/Skill-Neuron/src/trainer.py", line 62, in mlm_train_step
    outputs = self.model(sentences)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aflah20082/Skill-Neuron/src/modelzoo.py", line 134, in forward
    prompt_attention_mask=torch.ones((inputs_embeds.shape[0],self.prompt_size)).cuda()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

I checked and there is about 30 gigs of free GPU available. I also checked I'm on the right device. Do you have any idea what might be going wrong and how much GPU did it take at any one time in your experiments?

**Comment by aflah02** [comment]
It was a CUDA error on my end however there seem to be a lot of memory leakages as it keeps taking more and more GPU Space eventually causing OOM. Even 30 gigs of GPU are quickly taken up during prompt tuning @Bakser @WhenWen any ideas?

**Comment by WhenWen** [comment]
Hi! We haven't encountered this bug in our experiments. Can you share with us more specific information about your environments and the kind of device you are on?

**Comment by aflah02** [comment]
Hi @WhenWen 
Sorry I think I misread the errors. It turns out the batch size was the issue and the 128 one gives an OOM error in step 1 but 64 works on a A6000 (might be worth mentioning in the README). I have another question too 

The Prompt Tuning command did not create any saves while the subsequent commands did any ideas what might be wrong? I used this command:

```
!python /home/aflah20082/Skill-Neuron/src/train.py\
        --task_type founta\
        --data_path /home/aflah20082/Skill-Neuron/data/founta\
        --save_to /home/aflah20082/Skill-Neuron/founta\
        --bz 128\
        --eval_every_step 2000\
        --model_type RobertaPrompt
```

Here founta is the name of my dataset and I expected a directory named founta would be created according to the README with the backbone save but only a log file is saved there

Also is there any use for these backbones apart from pruning? I was under the impression the prompts are used to get the activation and baseline activation by reading the paper but even though no saves were generated from the first step the other steps did work, but that doesn't seem to make sense to me if the outputs of the first step aren't saved or used somehow

**Comment by aflah02** [comment]
Ah no need to answer the second question torch.load works

**Comment by aflah02** [comment]
For anyone visiting from the future in my experiments using the directory name as example solved the issue, I haven't explored why maybe it's just a saving issue or maybe I did something wrong!
